name: Build and Run Docker Workflow

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            -t my-docker-image .

      - name: Run Docker container and push tag
        run: |
          docker run --rm \
            -e GH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            my-docker-image
