name: Build and Run Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} -t my-docker-image .

      # Optionally push the image to Docker Hub or any other registry
      - name: Push Docker image
        run: |
          docker push my-docker-image

      # Run the workflow with the token
      - name: Run GitHub Actions workflow
        run: |
          docker run --rm my-docker-image

