name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Run Docker Container
        env:
          GITHUB_TOKEN: "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"
          GITHUB_REPO: "atulghodmare777/argo-proj"
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${GITHUB_TOKEN} \
            -e GITHUB_REPO=${GITHUB_REPO} \
            my-docker-image
