name: Build and Run Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sleep for GitHub to recognize new workflows
        run: sleep 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            --build-arg TAG_NAME=v1.0.2 \
            -t my-docker-image .

      - name: Run Docker container and trigger second workflow
        run: |
          docker run --rm \
            -e GH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            -e TAG_NAME=v1.0.2 \
            my-docker-image
