name: Second Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  run-second:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print tag that triggered workflow
        run: echo "Triggered by tag ${{ github.ref }}"
