name: Second Workflow

on:
  workflow_dispatch:

jobs:
  run-second:
    if: github.actor == 'atulghodmare777' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run second job
        run: echo "Hello from the second workflow triggered by ${{ github.actor }} on ${{ github.ref }}"
