name: Second Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  run-second:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show tag message
        run: echo "Triggered by tag ${{ github.ref }}"
