name: Second Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run workflow for'
        required: true

jobs:
  run-second:
    if: startsWith(github.event.inputs.tag, 'v') || startsWith(github.event.inputs.tag, 'release-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show the tag
        run: echo "Triggered by tag: ${{ github.event.inputs.tag }}"

